# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            SpaceMonkeyPants
tagline:          It Aint Rocket Science
url:              http://spacemonkeypants.github.io
paginate:         1
baseurl:          /
author:
  name:           Spacemonkeypants
  url:            https://twitter.com/spacemonkeypants
  email:          spacemonkeypants@buggyasfuck.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/spacemonkeypants/spacemonkeypants.github.io

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
